# Generated by Django 3.2.13 on 2022-05-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255, verbose_name='学员姓名')),
                ('studentAge', models.IntegerField(blank=True, null=True, verbose_name='学员年龄')),
            ],
            options={
                'verbose_name': '学员信息管理',
                'verbose_name_plural': '学员信息管理',
            },
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='考试总分')),
                ('remark', models.CharField(max_length=16, verbose_name='备注')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student', verbose_name='学生信息')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息列表',
            },
        ),
        migrations.CreateModel(
            name='ExamDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('className', models.CharField(max_length=16, verbose_name='科目')),
                ('ExamInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.examinfo', verbose_name='考试记录')),
            ],
            options={
                'verbose_name': '考试详情',
                'verbose_name_plural': '考试详情',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=16, verbose_name='联系方式')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student', verbose_name='学生信息')),
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式列表',
            },
        ),
    ]
